"""admin

Revision ID: 3f1ef16870f4
Revises: be095a90f80b
Create Date: 2024-10-27 18:12:39.758507

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3f1ef16870f4"
down_revision = "be095a90f80b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "admin", sa.Boolean(), nullable=False, server_default=sa.text("0")
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("user", schema=None) as batch_op:
        batch_op.drop_column("admin")

    # ### end Alembic commands ###
