"""update things

Revision ID: 6d34d4abeaa8
Revises: bdf8b0f0321d
Create Date: 2024-11-22 08:38:13.116857

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d34d4abeaa8'
down_revision = 'bdf8b0f0321d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_strategy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('param1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('param2', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('stop_loss', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_strategy', schema=None) as batch_op:
        batch_op.drop_column('stop_loss')
        batch_op.drop_column('param2')
        batch_op.drop_column('param1')

    # ### end Alembic commands ###
