"""add features to do websocket

Revision ID: e9f5ec0feed2
Revises: 9990661ac62c
Create Date: 2024-11-12 01:38:29.150780

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9f5ec0feed2'
down_revision = '9990661ac62c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_strategy', schema=None) as batch_op:
        batch_op.add_column(sa.Column('target_price', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user_strategy', schema=None) as batch_op:
        batch_op.drop_column('target_price')

    # ### end Alembic commands ###
